name: namespace Cyber_Security_Chatbot CI


on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore "Cyber Security Chatbot.sln"
      
      - name: Build Project
        run: msbuild "Cyber Security Chatbot.sln" /p:Configuration=Release

      - name: Check Code Formatting
        run: |
          dotnet format --verify-no-changes "Cyber Security Chatbot.sln"
          if ($LASTEXITCODE -ne 0) {
            throw "Code formatting issues detected. Please fix them before proceeding."
          }
